name: Publish 'xformers-cu124' to Docker Hub

on: 
  workflow_dispatch: # Can be manually triggered
    inputs:
      CUDA_ARCH_LIST:
        description: 'TORCH_CUDA_ARCH_LIST'
        required: true
        type: string
        default: "5.2+PTX;6.0;6.1+PTX;7.5;8.0;8.6;8.9;9.0+PTX"
      MAX_JOBS:
        description: 'MAX_JOBS to compile'
        required: true
        type: string
        default: "1"

jobs:

  build-images:
    environment: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      - 
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      -
        name: Build and push 'xformers-cu124'
        uses: docker/build-push-action@v6
        with:
          context: ./xformers-cu124
          # Build slowly but less crash on GitHub CI.
          build-args: |
            TORCH_CUDA_ARCH_LIST=${{ inputs.CUDA_ARCH_LIST }}
            MAX_JOBS=${{ inputs.MAX_JOBS }}
          tags: yanwk/comfyui-extras:xformers-cu124
          push: true
